# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'quotr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for quotr
  pod 'Alamofire', '~> 4.0'
  pod 'SnapKit', '~> 3.1.2'

end
